#include "pomp_lib.h"

struct ompregdescr omp_rd_1 = {
  "parallelfor", "", 0, "simpar-omp.c", 54, 54, 58, 58
};

#define POMP_DLIST_00001 shared(omp_rd_1)

struct ompregdescr omp_rd_2 = {
  "parallelfor", "", 0, "simpar-omp.c", 76, 76, 80, 80
};

#define POMP_DLIST_00002 shared(omp_rd_2)

struct ompregdescr omp_rd_3 = {
  "parallelfor", "", 0, "simpar-omp.c", 81, 81, 89, 89
};

#define POMP_DLIST_00003 shared(omp_rd_3)

struct ompregdescr omp_rd_4 = {
  "parallelfor", "", 0, "simpar-omp.c", 90, 90, 91, 91
};

#define POMP_DLIST_00004 shared(omp_rd_4)

struct ompregdescr omp_rd_5 = {
  "parallelfor", "", 0, "simpar-omp.c", 100, 100, 104, 104
};

#define POMP_DLIST_00005 shared(omp_rd_5)

struct ompregdescr omp_rd_6 = {
  "parallelfor", "", 0, "simpar-omp.c", 105, 105, 137, 137
};

#define POMP_DLIST_00006 shared(omp_rd_6)

struct ompregdescr omp_rd_7 = {
  "parallelfor", "", 0, "simpar-omp.c", 138, 138, 139, 139
};

#define POMP_DLIST_00007 shared(omp_rd_7)

