#include "pomp_lib.h"

struct ompregdescr omp_rd_1 = {
  "parallelfor", "", 0, "simpar-omp.c", 65, 65, 70, 70
};

#define POMP_DLIST_00001 shared(omp_rd_1)

struct ompregdescr omp_rd_2 = {
  "parallelfor", "", 0, "simpar-omp.c", 71, 71, 81, 81
};

#define POMP_DLIST_00002 shared(omp_rd_2)

struct ompregdescr omp_rd_3 = {
  "parallelfor", "", 0, "simpar-omp.c", 89, 89, 92, 92
};

#define POMP_DLIST_00003 shared(omp_rd_3)

struct ompregdescr omp_rd_4 = {
  "parallelfor", "", 0, "simpar-omp.c", 93, 93, 98, 98
};

#define POMP_DLIST_00004 shared(omp_rd_4)

struct ompregdescr omp_rd_5 = {
  "parallelfor", "", 0, "simpar-omp.c", 99, 99, 135, 135
};

#define POMP_DLIST_00005 shared(omp_rd_5)

struct ompregdescr omp_rd_6 = {
  "parallelfor", "", 0, "simpar-omp.c", 166, 166, 169, 169
};

#define POMP_DLIST_00006 shared(omp_rd_6)

