#include "pomp_lib.h"

struct ompregdescr omp_rd_1 = {
  "parallelfor", "", 0, "simpar-omp.c", 68, 68, 74, 74
};

#define POMP_DLIST_00001 shared(omp_rd_1)

struct ompregdescr omp_rd_2 = {
  "parallelfor", "", 0, "simpar-omp.c", 75, 75, 79, 79
};

#define POMP_DLIST_00002 shared(omp_rd_2)

struct ompregdescr omp_rd_3 = {
  "parallelfor", "", 0, "simpar-omp.c", 88, 88, 91, 91
};

#define POMP_DLIST_00003 shared(omp_rd_3)

struct ompregdescr omp_rd_4 = {
  "parallelfor", "", 0, "simpar-omp.c", 92, 92, 97, 97
};

#define POMP_DLIST_00004 shared(omp_rd_4)

struct ompregdescr omp_rd_5 = {
  "parallelfor", "", 0, "simpar-omp.c", 123, 123, 126, 126
};

#define POMP_DLIST_00005 shared(omp_rd_5)

struct ompregdescr omp_rd_6 = {
  "parallelfor", "", 0, "simpar-omp.c", 127, 127, 137, 137
};

#define POMP_DLIST_00006 shared(omp_rd_6)

struct ompregdescr omp_rd_7 = {
  "parallelfor", "", 0, "simpar-omp.c", 168, 168, 171, 171
};

#define POMP_DLIST_00007 shared(omp_rd_7)

